#!/bin/bash

### This script is called before the user installs the application.

apt update
apt install -y tmux
# curl -kL https://github.com/tsl0922/ttyd/releases/latest/download/ttyd.$(uname -m) -o /usr/bin/ttyd
# chmod +x /usr/bin/ttyd

exit 0