#!/bin/bash

### This script is called before the user upgrades the application.

curl -kL https://github.com/tsl0922/ttyd/releases/latest/download/ttyd.$(uname -m) -o /usr/bin/ttyd
chmod +x /usr/bin/ttyd 2>/dev/null
[ ! -x /usr/bin/ttyd ] && echo "Failed to install ttyd" >$TRIM_TEMP_LOGFILE && exit 1

apt update
apt upgrade -y tmux
[ $? -ne 0 ] && echo "Failed to upgrade tmux" >$TRIM_TEMP_LOGFILE && exit 1

exit 0
