#!/bin/bash

### This script is called after the user upgrades the application.

# Update configuration based on wizard inputs
if [ -n "${wizard_ssl_cert:-}" ] || [ -n "${wizard_ssl_cert_key:-}" ]; then wizard_protocol="https"; else wizard_protocol="http"; fi
sed -i "s|\"protocol\":.*,$|\"protocol\": \"${wizard_protocol:-http}\",|g" ${TRIM_APPDEST}/ui/config
sed -i "s|\"port\":.*,$|\"port\": \"${wizard_port:-28256}\",|g" ${TRIM_APPDEST}/ui/config
sed -i "s|\"url\":.*,$|\"url\": \"${wizard_base_path:-/}\",|g" ${TRIM_APPDEST}/ui/config

psql -U postgres -d appcenter -c "UPDATE app_service SET url='${wizard_protocol:-http}://\${host}:${wizard_port:-28256}${wizard_base_path:-/}', default_url='${wizard_protocol:-http}://\${host}:${wizard_port:-28256}${wizard_base_path:-/}' WHERE service_name LIKE '${TRIM_APPNAME}.%';"

exit 0
