#!/bin/bash

### This script is called after the user uninstalls the application.

# Restore the original mount.ntfs symlink to ntfs-3g
rm -f /usr/sbin/mount.ntfs && ln -sf "mount.ntfs-3g" "/usr/sbin/mount.ntfs"

# Remove ntfs3 module and related files
rm -f /etc/modules-load.d/ntfs3.conf || true
rm -f /usr/lib/modules/${KVER}/updates/fs/ntfs3.ko 2>/dev/null || true
depmod -a || true

# Restart systemd-modules-load.service to load the module
systemctl restart systemd-modules-load.service

exit 0
