#!/bin/bash

### This script is called after the user change environment variables in application setting page.

sed -i "s|\"port\":.*,$|\"port\": \"${wizard_port:-38356}\",|g" ${TRIM_APPDEST}/ui/config

exit 0
